FROM python:3.12-slim AS build

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt update && apt install -y ffmpeg

# Downloading: "https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/955717e8-8726e21a.th" to /root/.cache/torch/hub/checkpoints/955717e8-8726e21a.th
# Downloading: "https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/955717e8-8726e21a.th" to /tmp/hub/checkpoints/955717e8-8726e21a.th