services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    env_file: ".env"
    command: server /data --console-address ":9001"
    restart: always

volumes:
  data: